default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index"}
    methods: GET

default_teste:
    path: /provas
    defaults: { _controller: "AppBundle:Default:provas"}
    methods: POST

default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login"}
    methods: POST