app_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: /

user_default:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user

task_default:
    resource: "@AppBundle/Resources/config/routing/task.yml"
    prefix: /task

